### ISSUE TITLE
Can't install this plugin

### ISSUE THREAD

**Issue by akz92** [vutran/dext-darwin-applications-plugin#1]
I'm trying to install this plugin using `dpm` but the installation seems to get stuck, I killed the installation after 15 minutes.

**Comment by vutran** [comment]
It looks like this is an issue coming from [`dext-core-utils`](https://github.com/vutran/dext-core-utils). For some reason, it looks like the spawn [`npm install`](https://github.com/vutran/dext-core-utils/blob/develop/src/api/index.js#L70) process is failing somewhere which we currently have no easy way to tell.

I need to do more digging on why that is but in the mean time, you should be able to manually run `npm install` in the plugin's directory and then reboot Dext.

```
$ cd ~/.dext/plugins/dext-darwin-applications-plugin

$ npm install
```

**Comment by akz92** [comment]
Running `npm install` manually and rebooting Dext didn't help =/

**Comment by vutran** [comment]
What version node are you running? @akz92

**Comment by akz92** [comment]
I'm running node v7.4.0 and npm v4.0.5

**Comment by vutran** [comment]
@akz92 Try installing the latest version of `dext-cli` (v0.4.0) which is just release, then retry installing this plugin.

`v0.4.0` should pipe the child process (`npm install` in the plugin directory) into a null device which should enable `dpm` to finish and close itself.

Let me know how it goes.

**Comment by akz92** [comment]
The installation was successful! 😀

**Comment by vutran** [comment]
Closing this since this seems to be fixed. Leaving #2 opened since it's a different bug.
