### ISSUE TITLE
The search doesn't return any results

### ISSUE THREAD

**Issue by akz92** [vutran/dext-darwin-applications-plugin#2]
After installing the plugin I tested it on the latest Dext release (v0.7.1) and the search didn't return any results. When I tested on Dext's develop branch I got these errors:

```
Jan 19 00:43:47  Electron[97168] <Error>: ImageIO: CGImageDestinationFinalize image destination musthave at least one image
2017-01-19 00:43:47.600 Electron[97168:807598] CGImageDestinationFinalize failed for output type 'public.tiff'
Jan 19 00:43:47  Electron[97168] <Error>: ImageIO: CGImageSourceCreateWithData data parameter is nil
```

**Comment by vutran** [comment]
@akz92 What version OS X are you currently running?

**Comment by akz92** [comment]
I'm running v10.11.6

**Comment by vutran** [comment]
@akz92 I'll be looking into this issue sometimes this week. I'm actually running the same version of OS X and can't seem to replicate the issue.

OS X: `10.11.6`
Node: `7.4.0`
npm: `4.0.5`

If you run `npm install` in the `~/.dext/plugins/dext-darwin-applications-plugin` directory, are you receiving any errors/warnings?

**Comment by akz92** [comment]
I'm running npm `4.1.1` but I installed `4.0.5` to use the same version you use. I don't get any errors when I run 'npm install`, but I do get a couple warnings: https://gist.github.com/akz92/cc6fb8a1f63c3bcb374669dd6df8db8f

Let me know if there's anything else I can do to help :)

**Comment by vutran** [comment]
@akz92 By any chance are you running Dext `v0.7.1` or from the `develop` branch? I have yet to cut a release for the latest version of the Dext app itself with the last the last round of commits that adds support for non-keyword plugins which this plugin relies on.

**Comment by akz92** [comment]
I'm running from the `develop` branch and getting the following errors when I search for an application:
```
Jan 25 11:14:01  Electron[43465] <Error>: ImageIO: CGImageDestinationFinalize image destination must have at least one image
2017-01-25 11:14:01.255 Electron[43465:2728390] CGImageDestinationFinalize failed for output type 'public.tiff'
Jan 25 11:14:01  Electron[43465] <Error>: ImageIO: CGImageSourceCreateWithData data parameter is nil
```

**Comment by vutran** [comment]
@akz92 I'm still looking into this. It looks to be an issue with my [`mac-icons`](https://github.com/vutran/mac-icons) package. Can you try cloning that repo and running the test on your machine and see if it passes?

**Comment by akz92** [comment]
I get an error when running the tests of the `mac-icons` package. [Here's the npm-debug.log](https://gist.github.com/akz92/50c1c3e4131fcb66bc88238d23564304)

**Comment by iansinnott** [comment]
Also seeing this issue. 

* Node: `v6.9.1`
* NPM: `v4.0.5`
* OSX: `10.11.6`

Super excited about Dext. Can't wait to move from Alfred to something more extensible like this 😄

**Comment by vutran** [comment]
It looks like the issue lies in the `mac-icons` package so I will have to disable that dependency for now. As an alternative, circle letter icons will be shown in place of the actual system icon until the the next version of Electron when a native fetch icon API is implemented (see: https://github.com/electron/electron/pull/7851)

**Comment by vutran** [comment]
This is now fixed in the latest version.
